#!/usr/bin/env node
// Builds test/fixtures/season-2025.js — a real, COMPLETED NFL season (regular +
// postseason) used as the truth fixture for standings, seeding, and bracket tests.
//
// PLAYBOOK §7: prefer real data as the fixture. A finished season contains the edge
// cases you'd never invent — ties, identical-record tiebreaks, a full single-elim
// bracket with a known Super Bowl winner — that a synthetic fixture (built from your own
// assumptions) sails right past. Re-run when you want to refresh it:
//
//   node test/fixtures/build.mjs
import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { fetchTeams } from '../../scripts/lib/espn.mjs'
import { fetchSchedule } from '../../scripts/fetch-schedule.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const SEASON = 2025

const teams = await fetchTeams('football/nfl')
const games = await fetchSchedule(teams, SEASON)
const reg = games.filter((g) => g.seasonType === 'regular').length
const post = games.filter((g) => g.seasonType === 'postseason').length
console.log(`${SEASON}: ${games.length} games (${reg} regular, ${post} postseason)`)

await writeFile(
  join(HERE, 'season-2025.js'),
  `// GENERATED by test/fixtures/build.mjs — a completed NFL season, used as the truth\n` +
    `// fixture for standings/seeding/bracket tests. ${reg} regular + ${post} postseason games.\n` +
    `export const GAMES_2025 = [\n` +
    games.map((g) => `  ${JSON.stringify(g)},`).join('\n') +
    `\n]\n`
)
console.log('→ test/fixtures/season-2025.js')
